"""
Centralised configuration for backend paths and environment variables.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Core project locations
CONFIG_DIR = Path(__file__).resolve().parent
BACKEND_DIR = CONFIG_DIR.parent
PROJECT_ROOT = BACKEND_DIR.parent
ENV_FILE = PROJECT_ROOT / ".env"


def _load_environment() -> None:
    """
    Load environment variables from the project-level .env file if present.

    Falls back to a tiny parser when python-dotenv is not available so that we
    still pick up the expected key/value pairs across developer machines.
    """
    if ENV_FILE.exists():
        if load_dotenv:
            load_dotenv(ENV_FILE)
            return

        for raw_line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())


def get_env(key: str, default: Optional[str] = None) -> Optional[str]:
    """Wrapper so other modules do not access os.environ directly."""
    return os.getenv(key, default)


_load_environment()

# Shared filesystem locations
ASSETS_DIR = Path(get_env("ASSETS_DIR", PROJECT_ROOT / "assets")).resolve()
CARD_DATABASE_PATH = Path(
    get_env("CARD_DATABASE_PATH", ASSETS_DIR / "card_database.json")
).resolve()
ELIXIR_COST_PATH = Path(
    get_env("ELIXIR_COST_PATH", ASSETS_DIR / "elixir_cost.json")
).resolve()
TEMPLATES_DIR = Path(get_env("TEMPLATES_DIR", ASSETS_DIR / "templates")).resolve()
CARD_IMAGES_DIR = Path(get_env("CARD_IMAGES_DIR", ASSETS_DIR / "card_images")).resolve()
WEIGHTS_DIR = Path(get_env("WEIGHTS_DIR", ASSETS_DIR / "weights")).resolve()
EMBEDDINGS_CACHE_DIR = Path(
    get_env("EMBEDDINGS_CACHE_DIR", ASSETS_DIR / "embeddings_cache")
).resolve()

# Configuration artefacts generated by calibration steps
SAVED_CROP_PATH = Path(
    get_env("SAVED_CROP_PATH", CONFIG_DIR / "saved_crop.json")
).resolve()
FRIENDLY_CROP_PATH = Path(
    get_env("FRIENDLY_CROP_PATH", CONFIG_DIR / "friendly_crop.json")
).resolve()
WINDOW_OFFSETS_PATH = Path(
    get_env("WINDOW_OFFSETS_PATH", CONFIG_DIR / "window_offsets.json")
).resolve()
